#!/bin/bash

#aliases for creating files
alias create='touch README.md app.py'

#alias for reading the readme file
alias readme='vi README.md'

#alias for reading the app file
app='vi app.py'

#alias for testing the written code 
pyt='python3 app.py'
